language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: RP9GHsBLqSpAZmKVQRyJyw5Pv/D3FxRT/vZ2PzSQPRMSTvW3ktndNt6A8mIPR0uyaKZQ38XyaQzhvh7/UpDypEpPA9j2yyUJ4zV+IBSu6DVK56Sb8C5qPz61qxfxNTl03XATw/fZ/JMO/d/a+3N02GJTVCF6dL0gNOOTrj9vxwBMDmnnN0FHOEk1a2PcXrulOt2MfCrrLElT02eu2bGRZfvhNOgl+bgdtU9e359LlO1SDcOOtH/Mu3o7kT6WrI6GnvkhlR3hbXte/1637+BhWs8ZNKCFKSlRX0LYQh4R+H6tuwaGMphIeId3PgLsiikVtguBIoEk6xEoUsTSlPSZmN18Sgchatq4NmsHHBCNEKTBJFJZO6S3k88Iqy1JHdbZRE/kLgteOE//YjhcftRhGf/QwwLtSsMherz3Vj4gi0oSGMUb1XvnYAN8qCCvXwa3V57kMGBRuC91hgkZVe/jAtDHoEU6gdMlEKbLbGyWdBLEY/aCgPQ4J0KKBRSnHspr0qcdV5kAVZbe+pRRpJnVqrK6kUmD8RIA9PVjZUK80sNEU9K/0ZXHCWNib7I0WImy38qJDM1bH/G46O2JYfRZLpWTXXvd1hXp0aPBDKyvxopEBLEJHczxlKScUaMpPa7GpJPKi3EnEXhv4uoVSxF/0j6jLm8xewvdmrSxtQJr9gc=
  app: nameless-beyond-85779
