language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: Sw8bTbbGmcyf9SwwUVnc+LVvrDX2wSfeN53+/EBQmTDMLDGSkUNvhzPXOlXeU8DArQZNs1rk2fsdJioc0igSDMUb0IYjS2OBI+jDvzHvhO9JDUHrc0IMnfZvJkb3X3SZelJZr+fYd3ZR871u7qYVxtxr0MzGYkGZG/f98d14FYb1IUgB+0SN49QqjVP2LOgartoasXyWvYVy1Q+YmuOjkcaXy6+woajUecCJo5QjbKyDUgCZ1ARlphjLfXMY4b+WpxrCtPv8oAdSxhwBhEd+jeDhpvLeoTkRWl0t+gcgS/dyeImryG7I4l5TqOXupftuEEMfWvBrozbsno1fmZrNiqAx7ND5l1ILzJAPCBZinS09A+/6gO4LmJb3zKkW5HMdYs3RwJhkv1t8SMRw7CwbNf+rKZWJzXWG8W4PNDbSFVSU3lqt4xRKFfdt+tdLEf1bRRZCB0RQcF1TBvNRikZsCP5SdHez5fkayi8BD62zwoDABrUf5Gie7yFRO9f360IMmDb+sZUuUgMRF7HOP2g8ODDnFmZOmJGF+s+pN9+0tCcJ8KpQLEPEc2sPEC67r6U1Dqu7j/ORgAjKyuv+AKXmgdIDATCEjuKOY+a+REjB+b/61gMmLewWEP+iL01fRL0BigNOg5oRkQ06Mr2nev1MLQ7yYFFSJE3LysxdSDITLfQ=
  app: nameless-beyond-85779
