language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: cAO0gI3lJiVaqx2iej3u2IIQOfryXrWMcUqJ8axd/g8aIfY2du+hK0c1gz5sFsofp8o/oKUwPMqJeTt25fH5AQxxhhH1EMMgeGmvyay2VA/qC81fiA+ctmGpEZ8ZfXxc98GtJLoxsYkQGBVwnaL+aAiVSa8PpJryaRtuavWp6Lxh4Q6+OE3GBae7BRY9XI8o+8rP0OQz71trHmhFgh6jdf0CVni10WV/FnAtU6lgh4nuBlt89leXR+m3Ln6FTOTaGnElXs6+v0IGCDdTVeKIMegg1iEO5joiAx0N7Zeu3dEmAQFI31Plb0ydSk45MYuIWLx5fOCTkWetvfFK1BNu6T0P18iCPxdMKpcvY8z92Bkw+lTHruurLtJ00pQzzMsgdmR6xfbRyXQPsDXxeN//ZPQgT/kv0IIUdqL/37Se2qQP8mqGrnFyxtvqENtCv+YbfWYEY2IFe/SaQl+eVeeOo3q24DM2fstk2RF5kZDkyEaM2witJRbBWOurDbgwujdGnf2vrZCmm3k3org34pW/kmbN8Tn4Ua3s5n7znLVMwcdxLE5gxXDuyufI7rn53CQqi78EIS7/NgDuhbYSXQmocwBRWClXiyvt96wBAGRvY+qgJLM1RkYmCjDyBJwRFRnzx54b/J44fkGqWCPuIYQRxcEo01nGYnUy6VGBJmGQ6ow=
  app: nameless-beyond-85779
