language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: 05Xtfblb6yVYQLMYEJbe3WdiMO0ryy5KnYrKiBrDgEf7TaYE0fi/LSbRQX3IJ6RPsmZN2Ub1kImxoh9qs2aI+GHgF4xIQm+bIJXynK4dVH6UBhG9otEpBq7h3j48lBXMjmqwNyrCYQbn+gpwJ/BovFVWEtoSwDFWjef0UeLSs1wt8erznG4IfEQluMpBJLmCOqEWWoY5vHvg/i3w8uJqXiNeQegixUs8wI7GnVnsmS2mT0P4+eTJFZ6MeFUwrPKy2PhAZfStJLyT/OdY0RdEkyQi+x0ykCAN83gA2G43zoh4KhX0/tH5ERuW1Qwc7zB4nQgb5GF31bOgMmmCRoEFTVV2QLQ9YTwTGggX0qqYVuFQ/WRKitoroASDRXN2ZmxAedLPD++8iwgSUrsuKWBT1kfV6tvihL3R6S00V2ItYe/7Jk7Mwy1EqJ12ikL1jJM7ReiQbqLwOsgXeH3rdKjh7loFljDpNHKJgoOj6xwyuSRWER1pvuX0yRyakDGMbxCdz/uqJ6TSN1ElbG/a296nHlOOuCHwE43Q2KYtfLaT2Li7Pp9wBrUzfSrxX3e1pkdMZTQP3o/6H17cMuYkjZjZRNG/TOpdVeElezb1Vdr8rMBHuvlp546BPqOdUYrXmsgH4e6JaiYNooB+PDJt7BMMDSvv8tg15WaKVGRPdte7Hpc=
  app: nameless-beyond-85779
