language: node_js
node_js: node
services:
- mongodb
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: joOUCmxZ3ruf9kY+XApzz3rnEni8p2qk4AP7Dx23UgnnGq6gIbs1OO18FxQab3xGtP6I0triblyvHHLHfjlVNSjWRT7HR81lrxrm9nlPp5E4a0CL8pIMRwmMi8AVryVOBKT5EPVW7IC0OlwmcFSP2KiCiMRy9wr+s5DRfqBhCUm3xjaYWQMOsRfAoXARyKNBSC+nbh19mCFO7Qmf6LgKHff4C7uc0SlxCoYEJp6/8tu8MkcOevSVnrxqT8K3GlgofoMNFet5a57qcs8LCnjjgPrkIDOtKrS/Sv3aPtwkB1as1p/ocf41Cz8GEYft91Y7liXGqoT7GzlDCQ6Cknn1g9emC3wEFYAKKshuUzQYpr/5ymlKVY9GuU4NfQTycurv384Ew8HoOZ9tBLXL7u/KQFSeKfl6pAn7mNaO4y9IZKLcSO1C+HIY5H/pbyysMUTQ+KTVNB7LZUSgcCEnMJOGMqvsi0JjahYyAnWUbJqna7yxDap8504O2NH/hqT3BpAw8ern9m/S9Urr9iVbB1iA39QY8H/cM/PO5WhkXQIIvkALaNTQHXiCdoW/8ZRoSg+Uy7dR3PrHirMMyfcZAISi5shWHvGpiFVe1/DO8nUUKZNB05y1NcaT4AKXe5IRkc+ypdb23xgQceANNamopyaRg5U0dTCKEgKdQa4nhrVAifU=
  app: powerful-brook-78998
